name: Package Lambda Function

on:
  push:
    branches: [ main ]
    paths:
      - 'bots/strong_right/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.4'

    - name: Create Lambda package
      working-directory: ./firestore-to-s3
      run: |
        mkdir -p lambda_package
        pip install requests -t lambda_package
        cp -r bots/strong_right/* lambda_package/
        cd lambda_package
        zip -r ../lambda_function.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/sh-datrun-dp-gha
        aws-region: ap-southeast-1

    - name: Deploy to S3
      run: |
        aws s3 cp bots/strong_right/lambda_function.zip s3://data-robot/lambda/strong-right/lambda_function.zip
